# Generated by Django 3.0.5 on 2021-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('numb_of_subs', models.IntegerField(blank=True)),
                ('about', models.TextField()),
                ('price1', models.IntegerField(null=True)),
                ('price2', models.IntegerField(null=True)),
                ('price3', models.IntegerField(null=True)),
                ('slug', models.SlugField()),
                ('usr_pic', models.FileField(null=True, upload_to='usr-pic/')),
            ],
        ),
    ]
