# Generated by Django 3.0.5 on 2021-05-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='usr_pic',
            field=models.FileField(blank=True, null=True, upload_to='usr-pic/'),
        ),
    ]
