# Generated by Django 3.0.5 on 2021-05-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20210521_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='usr_pic',
            field=models.FileField(blank=True, null=True, upload_to='usr-pic/'),
        ),
    ]
