# Generated by Django 3.0.5 on 2021-05-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20210521_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='numb_of_subs',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='price1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='price2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='price3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='usr_pic',
            field=models.FileField(null=True, upload_to='usr-pic/'),
        ),
    ]
