# Generated by Django 3.0.5 on 2021-05-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20210521_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='numb_of_subs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='price1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='price2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='price3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
